name: Update Compiler Cache
inputs:
  token:
    description: Github token
    required: true
runs:
  using: composite
  steps:
    - name: Compiler Cache stats
      run: |
        ccache --evict-older-than 14400s
        ccache -sv
      shell: pwsh

    - name: Delete Previous Cache
      run: |
        if ("${{ github.ref_name }}" -eq "${{ github.event.repository.default_branch }}") {
          $cacheKey = $env:CCACHE_KEY
        } elseif ($env:CCACHE_MATCHED_KEY -eq $env:CCACHE_KEY) {
          $cacheKey = ""
        } else {
          $cacheKey = $env:CCACHE_KEY + '-tmp'
        }
        "CCACHE_SAVE_KEY=$cacheKey" >> $env:GITHUB_ENV
        if ($cacheKey) {
          gh extension install actions/gh-actions-cache
          gh actions-cache delete $cacheKey --branch ${{ github.ref_name }} --confirm
        }
        exit 0
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: pwsh

    - name: Save Cache
      if: env.CCACHE_SAVE_KEY
      uses: actions/cache/save@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ env.CCACHE_SAVE_KEY }}
