name: Update Compiler Cache
inputs:
  token:
    description: Github token
    required: true
runs:
  using: composite
  steps:
    - name: Compiler Cache stats
      run: |
        ccache --evict-older-than 1d
        ccache -sv
      shell: pwsh

    - name: Delete Previous Cache
      run: |
        if ("${{ github.ref_name }}" -eq "${{ github.event.repository.default_branch }}") {
          $saveKey = $env:CCACHE_KEY
        } elseif ($env:CCACHE_MATCHED_KEY -eq $env:CCACHE_KEY) {
          $saveKey = ""
        } else {
          $saveKey = $env:CCACHE_KEY + '-tmp'
        }
        "CCACHE_SAVE_KEY=$saveKey" >> $env:GITHUB_ENV
        if ($saveKey && $env:CCACHE_MATCHED_KEY) {
          gh extension install actions/gh-actions-cache
          gh actions-cache delete $saveKey --branch ${{ github.ref_name }} --confirm
        }
        exit 0
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: pwsh

    - name: Save Cache
      if: env.CCACHE_SAVE_KEY
      uses: actions/cache/save@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ env.CCACHE_SAVE_KEY }}
