name: Continuous Integration (CI) for Esp32

on:
  push:

  workflow_dispatch:

  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        variant: [esp32, esp32s2, esp32c3, esp32s3, esp32c2]
        idf_version: ["4.4", "5.0", "5.2"]
        include:
          - os: ubuntu-latest
            variant: esp32
            idf_version: "4.3"
        exclude:
          - variant: esp32c2
            idf_version: "4.4"
          - os: macos-latest
            idf_version: "4.4"
          - os: macos-latest
            idf_version: "5.0"
          - os: windows-latest
            idf_version: "5.0"

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ toJson(matrix) }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}

    env:
      SMING_HOME: ${{ github.workspace }}/Sming
      SMING_ARCH: Esp32
      SMING_SOC: ${{ matrix.variant }}
      INSTALL_IDF_VER: ${{ matrix.idf_version }}

    steps:
    - name: Fix autocrlf setting
      run: |
        git config --global --add core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      uses: ./.github/actions/install-tools

    - name: Restore Compiler Cache
      uses: ./.github/actions/ccache-restore

    - name: Build for ${{matrix.variant}}
      uses: ./.github/actions/build

    - name: Update Compiler Cache
      uses: ./.github/actions/ccache-update
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
