name: Continuous Integration (CI)

on:
  push:

  workflow_dispatch:

  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        variant: [esp8266, host, rp2040]
        toolchain: [gcc]
        include:
          - variant: esp8266
            arch: Esp8266
          - variant: host
            arch: Host
          - os: ubuntu-latest
            variant: host
            arch: Host
            toolchain: clang
          - os: ubuntu-latest
            variant: host
            arch: Host
            toolchain: gcc64
          - variant: rp2040
            arch: Rp2040

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ toJson(matrix) }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}

    env:
      SMING_HOME: ${{ github.workspace }}/Sming
      SMING_ARCH: ${{ matrix.arch }}
      SMING_SOC: ${{ matrix.variant }}
      CLANG_BUILD: ${{ matrix.toolchain == 'clang' && '15' || '0' }}
      BUILD64: ${{ matrix.toolchain == 'gcc64' && 1 || 0 }}

    steps:
    - name: Fix autocrlf setting
      run: |
        git config --global --add core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      uses: ./.github/actions/install-tools

    - name: Restore Compiler Cache
      uses: ./.github/actions/ccache-restore

    - name: Build for ${{ matrix.variant }}
      uses: ./.github/actions/build

    - name: Update Compiler Cache
      uses: ./.github/actions/ccache-update
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
